"""
End-to-End Scheduling Pipeline Test
Verifies:
  1. Email correctly classified as Scheduling
  2. Urgency score is on 0-100 scale
  3. A draft is created in draft_replies automatically
  4. The draft contains contextual content (mentions the sender's proposed times)
"""
import requests
import json
import time

BASE = "http://localhost:8000"

# ── Send a scheduling email ────────────────────────────────────────────────────
payload = {
    "sender_email": "colleague@corp.com",
    "subject": "Can we schedule a sync this week?",
    "content": (
        "Hi Tanishq, I wanted to check if you are free for a 30-minute call "
        "this week to discuss the Q2 roadmap. I am available Tuesday 3pm or "
        "Thursday 10am IST. Please let me know what works."
    ),
    "is_1on1": True
}

print("=" * 60)
print("STEP 1: Sending scheduling email to /process-email")
print("=" * 60)
r = requests.post(f"{BASE}/process-email", json=payload, timeout=35)
resp = r.json()

category = resp.get("command_package", {}).get("classification", "?")
score    = resp.get("command_package", {}).get("payload", {}).get("analysis", {}).get("urgency_score", "?")
action   = resp.get("command_package", {}).get("action", "?")
email_id = resp.get("email_action_id", "?")
draft_id = resp.get("scheduling_draft_id", "?")

print(f"  Category         : {category}")
print(f"  Urgency Score    : {score}%")
print(f"  Action           : {action}")
print(f"  email_actions.id : {email_id}")
print(f"  draft_replies.id : {draft_id}")

# ── Give n8n time to run its probe and post back ─────────────────────────────
print("\nWaiting 10 seconds for n8n to process and post back...")
time.sleep(10)

# ── Verify draft exists in Draft Hub ─────────────────────────────────────────
print()
print("=" * 60)
print("STEP 2: Verifying draft appeared in /drafts (Generated by n8n)")
print("=" * 60)
dr = requests.get(f"{BASE}/drafts", timeout=5)
drafts = dr.json().get("drafts", [])

found = [d for d in drafts if d.get("email_action_id") == email_id]
if found:
    d = found[0]
    print(f"  [PASS] Draft found! (Creator: n8n)")
    print(f"  draft id   : {d['id']}")
    print(f"  type       : {d['type']}")
    print(f"  recipient  : {d['recipient']}")
    print(f"  subject    : {d['subject']}")
    print(f"  status     : {d['status']}")
    print(f"  content snippet: {d['content'][:120]}...")
else:
    print(f"  [FAIL] No draft found in Draft Hub for email_action_id={email_id}")
    print(f"  Total drafts in DB: {len(drafts)}")

print()
print("=" * 60)
